export { ceil } from './lib/ceil';
export { countSteps } from './lib/count-steps';
export { floor } from './lib/floor';
export { inRange } from './lib/in-range';
export { isNear } from './lib/is-near';
export { lerp } from './lib/lerp';
export { loop } from './lib/loop';
export { map } from './lib/map';
export { norm } from './lib/norm';
export { overflow } from './lib/overflow';
export { round } from './lib/round';
export { clamp, unifyZero } from '@almaclaine/core';
